<?php

namespace App\Filament\Resources\Anggota\BiodataResource\Pages;

use App\Filament\Resources\Anggota\BiodataResource;
use Filament\Actions;
use Filament\Actions\Action;
use Filament\Resources\Pages\EditRecord;

class EditBiodata extends EditRecord
{
    protected static string $resource = BiodataResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\DeleteAction::make(),
        ];
    }

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }


    protected function getSaveFormAction(): Action
    {
        return parent::getSaveFormAction()
            ->color('success')
            ->label('simpan')
            ->icon('heroicon-o-check'); // TODO: Change the autogenerated stub
    }

    protected function getCancelFormAction(): Action
    {
        return parent::getCancelFormAction()
            ->label('Kembali'); // TODO: Change the autogenerated stub
    }
}
